#!/usr/bin/groovy

@Library('jenkins-common-lib') _

stage('test-sshCmd')
{
    node('master') { timestamps
    {
        def server = 'webap', cmd = 'ls /opt/app/lib'
        def config = ['path':'/opt/app/conf', 'file':'env.yml']
        def env = readYaml(
            file: config['path'] + "/" + config['file']
        )

        def stdout = new StringBuffer(), stderror = new StringBuffer()

        // コマンド組立
        def ssh_cmd = [
            ('ssh -i ' + env.session.ssh."${server}".identity),
            ('-p '     + env.session.ssh."${server}".port),
            (            env.session.ssh."${server}".user + '@' + env.session.ssh."${server}".host),
            (cmd)
        ].join(' ')

        // コマンド実行
        def proc = ssh_cmd.execute()

        // コマンド結果保存先設定
        proc.consumeProcessOutput(stdout, stderror)

        // コマンド結果出力が完了するまで待機
        proc.waitForProcessOutput()

        // 標準エラー出力が発生している場合は、標準エラー出力も返却する
        if(stderror.size() == 0)
        {
            println stdout
        }
        else {
            println stdout
            println stderror
        }
    }}
}
