#!groovy

@Library('jenkins-common-lib') _

node('master') { timestamps
{
    serverList = ['webap', 'batch']
    for (server in serverList)
    {
        serverList[ server ] =
        {
            stage('WU起動数判定[' + server + ']')
            {
                try
                {
                    // 開始メッセージ
                    printMsg('info', '-------------------------------------------------------')
                    printMsg('info', 'STAGE: WU起動数判定')
                    printMsg('info', '-------------------------------------------------------')
                    printMsg('info', 'Job Name: resource_monitor/wu_execute_cnt')
                    printMsg('info', 'Job Param: server = ' + server)

                    // ジョブ実行
                    build(
                        job:           'resource_monitor/wu_execute_cnt',
                        parameters:    [
                            text(name: 'server',  value: server)
                        ]
                    )

                    // ジョブ実行結果をコンソールに出力
                    showJobResult('wu_execute_cnt_' + server, 'stdout')

                    // ジョブ判定結果取得
                    result = readDataToFile('wu_execute_cnt_' + server)
                    jobResult['wu_execute_cnt_' + server] = result['wu_execute_cnt']
                }
                catch(Exception e)
                {
                    // ジョブ実行結果をコンソールに出力
                    showJobResult('wu_execute_cnt_' + server, 'stderror')
                    throw e
                }
            }
        }
    }
    parallel serverList

    stage('後処理')
    {
        //
        println jobResult
    }
}}
