#!groovy

@Library('jenkins-common-lib') _

node('master') { timestamps
{
    /**  UT試験
     *  期待する動作：引数に渡した変数がYaml形式のファイルに書き込まれること。
     */
    stage('test-case-1')
    {
        try
        {
            result = ['webap': 'faital']
            writeResultFile(result, 'test-case-1')
        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }

    /**  UT試験
      *  期待する動作：引数に渡した変数がYaml形式のファイルに書き込まれること。
      */
    stage('test-case-2')
    {
        try
        {
            server = 'batch'
            result = ["${server}": 'warning']
            writeResultFile(result, 'test-case-2')
        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }
    /**  UT試験
      *  期待する動作：引数に渡した変数がYaml形式のファイルに「追記」で書き込まれること。
      */
    stage('test-case-3')
    {
        try
        {
            server = 'batch'
            result = ["${server}": 'warning']
            writeResultFile(result, 'test-case-2')
        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }
}}
