#!groovy

@Library('jenkins-common-lib') _

node('master') { timestamps
{
    stage('前提条件')
    {
        // 書込対象のファイル
        temp = ['path':'/opt/var/jenkins/temp', 'file':'result_test-case-1.yml']

        // ファイルが存在していた場合、削除
        File f = new File(temp['path'] + "/" + temp['file'])
        if(f.exists())
        {
            f.delete()
        }

        // 書込対象のファイル
        temp = ['path':'/opt/var/jenkins/temp', 'file':'result_test-case-2.yml']

        // ファイルが存在していた場合、削除
        File ff = new File(temp['path'] + "/" + temp['file'])
        if(ff.exists())
        {
            ff.delete()
        }
    }

    /**  UT試験
     *  期待する動作：引数に渡した変数がYaml形式のファイルに書き込まれること。
     */
    stage('test-case-1')
    {
        try
        {
            result = ['webap': 'faital']
            writeResultFile(result, 'test-case-1')
        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }

    /**  UT試験
      *  期待する動作：引数に渡した変数がYaml形式のファイルに書き込まれること。
      */
    stage('test-case-2')
    {
        try
        {
            server = 'batch'
            result = ["${server}": 'warning']
            writeResultFile(result, 'test-case-2')
        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }
    /**  UT試験
      *  期待する動作：既に存在しているファイルは削除され、新たに引数に渡した変数で書き込まれること。
      */
    stage('test-case-3')
    {
        try
        {
            server = 'batch'
            result = ["${server}": 'nomal']
            writeResultFile(result, 'test-case-2')
        }
        catch(Exception e) {

            println 'result: NG'
            throw e
        }

        println 'result: OK'
    }
}}
