#!/usr/bin/groovy

@Library('jenkins-common-lib') _

stage('test-loadEnvConfig')
{
    node('master') { timestamps
    {
        def config_file = ['path':'/opt/app/conf', 'file':'config.yml']
        def config = readYaml(
            file: config_file['path'] + "/" + config_file['file']
        )

        echo "config.someProp ＝ ${config.someProp}"
        echo "config.someCategory.prop ＝ ${config.someCategory.prop}"
        echo "config.someCategory.arrayProp[0] ＝ ${config.someCategory.arrayProp[0]}"
        echo "config.someCategory.arrayProp[1] ＝ ${config.someCategory.arrayProp[1]}"
        echo "config.someCategory.arrayProp[2] ＝ ${config.someCategory.arrayProp[2]}"
    }}
}
