#!groovy

@Library('jenkins-common-lib') _

 node('master') { timestamps
{
   /** ジョブパラメータ取得ステージ
     * ・
     * ・
     * ・
     * ・
     * ・
     */
    stage('ジョブパラメータセット')
    {
        try
        {
            // 仮の値（null）をセット
            def server = null
        }
        catch(MissingPropertyException e)
        {
            // 呼び出されたジョブから引き継いだパラメータで後続ステージに進む
            printMsg('info', 'ジョブパラメータ「server」に「' + server + '」がセットされました。')
        }
        try
        {
            // 応答に制限時間を設定
            timeout(time: 60, unit: 'SECONDS')
            {
                // ユーザから入力を受け付ける
                userInput = input(
                    message        : '''\
                                     |リソース取得先サーバを選択してください。
                                     |（応答時間：60秒）'''.stripMargin(),
                    ok             : '選択する',
                    parameters     : [
                        choice(
                            name   : 'リソース取得先サーバ名:',
                            choices: 'web/apサーバ\nバッチサーバ'
                        )
                    ]
                )
            }
        }
        catch(Exception e)
        {
            // 制限時間内に変数の中身がnullから変わっていない場合は、例外を投げる
            printMsg('error', '入力されたパラメータが確認できません。応答時間内にリソース取得先サーバを選択してください。')
            throw e
        }

        printMsg('info','入力されたパラメータをチェックします。')

        // 入力されたデータに合わせて、処理用の値をセット
        if(userInput == 'web/apサーバ')
        {
            server = 'webap'
        }
        if(userInput == 'バッチサーバ')
        {
            server = 'batch'
        }

        printMsg('info', 'ジョブパラメータ「server」に「' + server + '」がセットされました。')
    }

   /** WU起動数判定ステージ
     * ・
     * ・
     * ・
     * ・
     * ・
     */
    stage('WU起動数判定')
    {
        // 開始メッセージ
        printMsg('info', '-------------------------------------------------------')
        printMsg('info', 'STAGE: WU起動数判定')
        printMsg('info', '-------------------------------------------------------')
        printMsg('info', 'Job Name: resource_monitor/wu_execute_cnt')
        printMsg('info', 'Job Param: server = ' + server)

        // AP設定ロード
        def config = loadAppConfig()

        // リソース取得実行
        def result = sshCmd(env, server, 'ls /opt/app/lib')

        // リソース判定
        switch(true)
        {
            // 標準エラー出力が返却されている場合
            case(result['stderror'] != null) as boolean:

                // 標準エラー出力をコンソールに出力
                printMsg('warning', result['stderror'])

                // 異常終了させる

                break

            // 危険域
            case(result['stdout'].contains(config.resource.monitor.wu.execute.faital.keyword)) as Boolean:

                // リソース取得結果をコンソールに出力
                printMsg('warning', result['stdout'])

                // 判定結果をファイルに出力
                result.put('wu_execute_cnt', 'faital')
                writeDataToFile(result, 'wu_execute_cnt_' + server)

                // メール通知
                emailext(
                    to       : config.mail.address.debug,
                    subject  : '${DEFAULT_SUBJECT}ABORT',
                    body     : '''<p>ジョブ走行中に予期せぬエラーが発生しました。</p>
                                  <p>解析をお願いします。</p>''',
                    attachLog: false,
                    mimeType : 'text/html'
                )

                break

            // 注意域
            case(result['stdout'].contains(config.resource.monitor.wu.execute.warning.keyword)) as Boolean:

                // リソース取得結果をコンソールに出力
                printMsg('warning', result['stdout'])

                // 判定結果をファイルに出力
                result.put('wu_execute_cnt', 'warning')
                writeDataToFile(result, 'wu_execute_cnt_' + server)

                // メール通知
                emailext(
                    to       : config.mail.address.debug,
                    subject  : '${DEFAULT_SUBJECT}ABORT',
                    body     : '''<p>ジョブ走行中に予期せぬエラーが発生しました。</p>
                                  <p>解析をお願いします。</p>''',
                    attachLog: false,
                    mimeType : 'text/html'
                )

                break

            // 正常域
            default:

                // リソース取得結果をコンソールに出力
                printMsg('info', result['stdout'])

                // 判定結果をファイルに出力
                result.put('wu_execute_cnt', 'normalend')
                writeDataToFile(result, 'wu_execute_cnt_' + server)

                break
        }
    }

   /** WU起動数判定ステージ
     * ・
     * ・
     * ・
     * ・
     * ・
     */
    stage('後処理')
    {
        // ジョブ結果をファイルに出力
        //writeDataToFile(result, 'result_resource_monitor_' + server)
    }
}}
