#!groovy

@Library('jenkins-common-lib') _

 node('master') { timestamps
{
   /** ジョブパラメータ取得ステージ
     * ・
     * ・
     * ・
     * ・
     * ・
     */
    stage('ジョブパラメータ取得')
    {
        try
        {
            // MissingPropertyException回避のため、仮の値（temp）をセット
            def server = 'temp'

            try
            {
                // 応答に制限時間を設定
                timeout(time: 20, unit: 'SECONDS')
                {
                    // ユーザから入力を受け付ける
                    def userInput = input(
                        message        :  '''\
                                     |リソース取得先サーバを選択してください。
                                     |（応答時間：10秒）'''.stripMargin(),
                        ok             : '選択する',
                        parameters     : [
                            choice(
                                name   : 'リソース取得先サーバ名:',
                                choices: 'web/apサーバ\nバッチサーバ'
                            )
                        ]
                    )
                }
            }
            catch(Exception e)
            {
                // 制限時間に応答したかどうかに関わらず、必ず通るルート（不思議）
                printMsg('info','入力されたパラメータをチェックします。')
            }

            try
            {
                // 入力されたデータに合わせて、処理用の値をセット
                if(userInput == 'web/apサーバ')
                {
                    server = 'webap'
                }
                else
                {
                    server = 'batch'
                }

                printMsg('info', '変数「server」に「' + userInput + '」がセットされました。')

            }
            catch(Exception e)
            {
                // 変数の中身がnullから変わっていない場合は、例外を投げる
                printMsg('error', '入力されたパラメータが確認できません。応答時間内にリソース取得先サーバを選択してください。')
                throw e
            }
        }
        catch(Exception e)
        {
            println userInput
            // 変数の宣言重複ができないことを利用して、引き継いだパラメータで後続ステージに進む
            printMsg('info', '変数「server」に「' + server + '」がセットされました。')
        }
    }
}}
